# Generated by Django 5.2.7 on 2025-10-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayExcercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField(default=12)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.day')),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excercises.excercise')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='excercise',
            field=models.ManyToManyField(through='routines.DayExcercise', to='excercises.excercise'),
        ),
    ]
